project first all code
MatviiGD/gridu pull request #1
Opened 2022-03-16 13:16 UTC by MatviiGD

2022-03-16 13:26 UTC, rzherebgrid commented on src/LessonOneSimpleTicTacToe/OccupiedCoordinateException.java
> +class OccupiedCoordinateException extends Exception {
Класна ідея зі своїми ексепшинами, але в такому випадку додай ще конструктор з якимось власним повідомленням. Бо інакше сенсу у власних ексепшинах нема

2022-03-16 13:29 UTC, rzherebgrid requested changes
Решта все гарно

2022-03-16 13:32 UTC, MatviiGD commented on src/LessonOneSimpleTicTacToe/OccupiedCoordinateException.java
> +class OccupiedCoordinateException extends Exception {
гаразд

2022-03-17 13:51 UTC, rzherebgrid approved these changes

2022-03-18 09:30 UTC, merged

2022-03-18 09:30 UTC, MatviiGD commented
Done