Third task
MatviiGD/gridu pull request #3
Opened 2022-03-23 16:47 UTC by MatviiGD

посилання на проект
https://hyperskill.org/projects/125?track=17

2022-03-23 19:38 UTC, rzherebgrid commented on src/LessonThreeMediumBattleship/Coordinate.java
> +    final int x;
Забув про інкапсуляцію, поля мають будуть приватними

2022-03-23 19:39 UTC, rzherebgrid commented on src/LessonThreeMediumBattleship/Coordinate.java
> +    Coordinate(String input) throws WrongLocationException {
Зазвичай конструктори не мають ні кидати ексепшини, ні робити валідацію вхідних параметрів. Просто this.x = x, this.y=y і тд

2022-03-23 19:40 UTC, rzherebgrid commented on src/LessonThreeMediumBattleship/Game.java
> +    Player player1;
Те саме що і в Coordinate класі

2022-03-23 19:41 UTC, rzherebgrid commented on src/LessonThreeMediumBattleship/Game.java
> +    void passTurn() {
Модифікатори доступу. default рідко використовується, public або private

2022-03-23 19:50 UTC, rzherebgrid requested changes

2022-03-23 19:50 UTC, rzherebgrid commented on src/LessonThreeMediumBattleship/Game.java
> +    void passTurn() {
Це стосується всіх методів у всіх класах

2022-03-23 19:50 UTC, rzherebgrid commented on src/LessonThreeMediumBattleship/Player.java
> +            } catch (ArrayIndexOutOfBoundsException ignored) {}
Catch має щось робити, як мінімум записати причину помилки, наприклад в консоль

2022-03-23 19:50 UTC, rzherebgrid commented on src/LessonThreeMediumBattleship/Player.java
> +        assert start_x == stop_x || start_y == stop_y;
assert в робочому коді рідко використовується, лише в тестах

2022-03-23 19:50 UTC, rzherebgrid commented on src/LessonThreeMediumBattleship/Player.java
> +        while (true) {
Я помиляюсь чи цей цикл завжди виконається лише один раз? Зчитав координату і break?

2022-03-23 19:50 UTC, rzherebgrid commented on src/LessonThreeMediumBattleship/Player.java
> +                if (board[y][x].equals("O")) {
Лайфхак: якщо порівнюєш щось з константним значенням, то завжди роби КОНСТАНТА.equals(...), в даному випадку "0".equals(board[y][x]). Таким чином уберігається від можливих NPE

2022-03-23 19:50 UTC, rzherebgrid commented on src/LessonThreeMediumBattleship/TooCloseException.java
> +class TooCloseException extends Exception {
Та ж помилка, що і в перших завданнях. Свої експешини мають нести якесь своє повідомлення, свою логіку обробки, інакше в них просто нема сенсу

2022-03-24 19:08 UTC, MatviiGD commented on src/LessonThreeMediumBattleship/Player.java
> +        while (true) {
цей цикл імітує ігру,посуті ти правий без нього програма буде не коректною

2022-03-29 07:57 UTC, rzherebgrid approved these changes

2022-03-29 07:57 UTC, rzherebgrid commented on src/LessonThreeMediumBattleship/Coordinate.java
> +        this.x=x;
Spaces missed. this.x = x

2022-03-29 07:57 UTC, rzherebgrid commented on src/LessonThreeMediumBattleship/Coordinate.java
> +        if (x > 9 || y < 0 || y > 9 || (input.length() == 3 && !input.endsWith("10"))) {
x > 9 || y < 0 || y > 9
I suppose this part should be put in brackets as well

2022-03-29 07:57 UTC, rzherebgrid commented on src/LessonThreeMediumBattleship/Coordinate.java
> +        this.x=x;
Spaces

2022-03-29 07:57 UTC, rzherebgrid commented on src/LessonThreeMediumBattleship/Game.java
> + private final Player player1;
Formatting. Use format code shortcut in IDEA

2022-03-29 07:57 UTC, rzherebgrid commented on src/LessonThreeMediumBattleship/MediumBattleshipMain.java
> +
Empty lines

2022-03-29 07:57 UTC, rzherebgrid commented on src/LessonThreeMediumBattleship/Player.java
> +    Player(String name) {
Public modifier missed

2022-03-29 07:57 UTC, rzherebgrid commented on src/LessonThreeMediumBattleship/Player.java
> +    Player(String name) {
Again, a lot of code in constructor

2022-03-29 07:57 UTC, rzherebgrid commented on src/LessonThreeMediumBattleship/Player.java
> +    void printBoards() {
public modifier

2022-03-29 11:01 UTC, rzherebgrid approved these changes

2022-03-30 06:52 UTC, merged