End of a hard task
MatviiGD/gridu pull request #4
Opened 2022-04-04 19:39 UTC by MatviiGD

2022-04-04 20:15 UTC, rzherebgrid requested changes

2022-04-04 20:15 UTC, rzherebgrid commented on src/lessonFour/Algorithm.java
> +abstract class Algorithm {
public

2022-04-04 20:15 UTC, rzherebgrid commented on src/lessonFour/Algorithm.java
> +    abstract String encrypt(String message, int key);
public

2022-04-04 20:15 UTC, rzherebgrid commented on src/lessonFour/Enigma.java
> +        if (outPath.equals("")) {
It's much better to have "".equals(outPath)

2022-04-04 20:15 UTC, rzherebgrid commented on src/lessonFour/Enigma.java
> +        if (data.equals("")) {  // prefer "-data" over "-in"
Same here

2022-04-05 07:58 UTC, rzherebgrid approved these changes

2022-04-05 08:27 UTC, MatviiGD commented
thank you

2022-04-05 08:27 UTC, merged