ChallengingTask
MatviiGD/gridu pull request #5
Opened 2022-04-14 16:44 UTC by MatviiGD

2022-04-15 11:00 UTC, rzherebgrid requested changes
1. Every method should have a modifier
2. A lot of If-else blocks without brackets

2022-04-15 11:00 UTC, rzherebgrid commented on src/ChallengingTaskCarSharing/Database.java
> +    public Connection connection;
private

2022-04-15 11:00 UTC, rzherebgrid commented on src/ChallengingTaskCarSharing/MenuService.java
> +    void addCompany() {
public?

2022-04-15 11:00 UTC, rzherebgrid commented on src/ChallengingTaskCarSharing/MenuService.java
> +                        var car = chooseElementFromList(cars);
Change var to Car, it's not good looking  to have type casting bellow

2022-04-21 12:25 UTC, rzherebgrid approved these changes

2022-04-22 07:28 UTC, merged

2022-04-22 07:28 UTC, MatviiGD commented
thank you